version: "2.2"

services:
  scheduler:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    container_name: scheduler
    environment: 
      RAVEN_CONFIG_DSN: "http://4d8d2a23c26a4a9e8c44f9f4b9c3b3d5:6a34464e42ca41c58ff424a3c821f50f@sentry.dev.trood.ru/7"
      RAVEN_CONFIG_RELEASE: "dev"
    ports:
      - "8000"
    networks:
      - test-network

  scheduler_postgres:
    image: postgres:9.5
    container_name: postgres.scheduler
    environment:
      CONTAINER_NAME: postgres.scheduler
    volumes:
      - ./postgres/${CONTAINER_NAME}/data:/var/lib/postgresql/data
      - ./postgres/${CONTAINER_NAME}/conf:/etc/postgresql
      - ./postgres/${CONTAINER_NAME}/logs:/var/log/postgresql
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: scheduler
      POSTGRES_USER: scheduler
      POSTGRES_PASSWORD: scheduler

    networks:
      - test-network

networks:
  test-network:
    driver: bridge